package uz.tripshare.domain.enumerators;

public enum Category {
    ADVENTURE, RELAXATION, WELLNESS,
    HONEYMOON, FAMILY, LUXURY,
    BUDGET, NATURE, CULTURAL, SAFARI,
    ROADTRIP, BEACH, CAMPING, BACKPACKING,
    HIKING, CRUISE, CULINARY, SPIRITUAL, SPORTS
}
